name: Docker Build & Push

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: runbgp
  DOCKER_CONTAINER_NAME: caddy-cloudflare-dns
  DOCKER_TARGET_PLATFORM: linux/amd64, linux/arm64, linux/arm/v8, linux/arm/v7

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.DOCKER_TARGET_PLATFORM }}
          push: true
          tags: |
            ghcr.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
            ghcr.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:${{ steps.prepare.outputs.tag }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_CONTAINER_NAME }}:latest
